/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/luolanzone/tunnel-example/apis/gateway/v1alpha1"
	scheme "github.com/luolanzone/tunnel-example/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MemberClusterInfosGetter has a method to return a MemberClusterInfoInterface.
// A group's client should implement this interface.
type MemberClusterInfosGetter interface {
	MemberClusterInfos() MemberClusterInfoInterface
}

// MemberClusterInfoInterface has methods to work with MemberClusterInfo resources.
type MemberClusterInfoInterface interface {
	Create(ctx context.Context, memberClusterInfo *v1alpha1.MemberClusterInfo, opts v1.CreateOptions) (*v1alpha1.MemberClusterInfo, error)
	Update(ctx context.Context, memberClusterInfo *v1alpha1.MemberClusterInfo, opts v1.UpdateOptions) (*v1alpha1.MemberClusterInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MemberClusterInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MemberClusterInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MemberClusterInfo, err error)
	MemberClusterInfoExpansion
}

// memberClusterInfos implements MemberClusterInfoInterface
type memberClusterInfos struct {
	client rest.Interface
}

// newMemberClusterInfos returns a MemberClusterInfos
func newMemberClusterInfos(c *GatewayV1alpha1Client) *memberClusterInfos {
	return &memberClusterInfos{
		client: c.RESTClient(),
	}
}

// Get takes name of the memberClusterInfo, and returns the corresponding memberClusterInfo object, and an error if there is any.
func (c *memberClusterInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MemberClusterInfo, err error) {
	result = &v1alpha1.MemberClusterInfo{}
	err = c.client.Get().
		Resource("memberclusterinfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MemberClusterInfos that match those selectors.
func (c *memberClusterInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MemberClusterInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MemberClusterInfoList{}
	err = c.client.Get().
		Resource("memberclusterinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested memberClusterInfos.
func (c *memberClusterInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("memberclusterinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a memberClusterInfo and creates it.  Returns the server's representation of the memberClusterInfo, and an error, if there is any.
func (c *memberClusterInfos) Create(ctx context.Context, memberClusterInfo *v1alpha1.MemberClusterInfo, opts v1.CreateOptions) (result *v1alpha1.MemberClusterInfo, err error) {
	result = &v1alpha1.MemberClusterInfo{}
	err = c.client.Post().
		Resource("memberclusterinfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(memberClusterInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a memberClusterInfo and updates it. Returns the server's representation of the memberClusterInfo, and an error, if there is any.
func (c *memberClusterInfos) Update(ctx context.Context, memberClusterInfo *v1alpha1.MemberClusterInfo, opts v1.UpdateOptions) (result *v1alpha1.MemberClusterInfo, err error) {
	result = &v1alpha1.MemberClusterInfo{}
	err = c.client.Put().
		Resource("memberclusterinfos").
		Name(memberClusterInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(memberClusterInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the memberClusterInfo and deletes it. Returns an error if one occurs.
func (c *memberClusterInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("memberclusterinfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *memberClusterInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("memberclusterinfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched memberClusterInfo.
func (c *memberClusterInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MemberClusterInfo, err error) {
	result = &v1alpha1.MemberClusterInfo{}
	err = c.client.Patch(pt).
		Resource("memberclusterinfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
