/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/luolanzone/tunnel-example/apis/gateway/v1alpha1"
	scheme "github.com/luolanzone/tunnel-example/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TunnelEndpointsGetter has a method to return a TunnelEndpointInterface.
// A group's client should implement this interface.
type TunnelEndpointsGetter interface {
	TunnelEndpoints() TunnelEndpointInterface
}

// TunnelEndpointInterface has methods to work with TunnelEndpoint resources.
type TunnelEndpointInterface interface {
	Create(ctx context.Context, tunnelEndpoint *v1alpha1.TunnelEndpoint, opts v1.CreateOptions) (*v1alpha1.TunnelEndpoint, error)
	Update(ctx context.Context, tunnelEndpoint *v1alpha1.TunnelEndpoint, opts v1.UpdateOptions) (*v1alpha1.TunnelEndpoint, error)
	UpdateStatus(ctx context.Context, tunnelEndpoint *v1alpha1.TunnelEndpoint, opts v1.UpdateOptions) (*v1alpha1.TunnelEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TunnelEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TunnelEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TunnelEndpoint, err error)
	TunnelEndpointExpansion
}

// tunnelEndpoints implements TunnelEndpointInterface
type tunnelEndpoints struct {
	client rest.Interface
}

// newTunnelEndpoints returns a TunnelEndpoints
func newTunnelEndpoints(c *GatewayV1alpha1Client) *tunnelEndpoints {
	return &tunnelEndpoints{
		client: c.RESTClient(),
	}
}

// Get takes name of the tunnelEndpoint, and returns the corresponding tunnelEndpoint object, and an error if there is any.
func (c *tunnelEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TunnelEndpoint, err error) {
	result = &v1alpha1.TunnelEndpoint{}
	err = c.client.Get().
		Resource("tunnelendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TunnelEndpoints that match those selectors.
func (c *tunnelEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TunnelEndpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TunnelEndpointList{}
	err = c.client.Get().
		Resource("tunnelendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tunnelEndpoints.
func (c *tunnelEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tunnelendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a tunnelEndpoint and creates it.  Returns the server's representation of the tunnelEndpoint, and an error, if there is any.
func (c *tunnelEndpoints) Create(ctx context.Context, tunnelEndpoint *v1alpha1.TunnelEndpoint, opts v1.CreateOptions) (result *v1alpha1.TunnelEndpoint, err error) {
	result = &v1alpha1.TunnelEndpoint{}
	err = c.client.Post().
		Resource("tunnelendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tunnelEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a tunnelEndpoint and updates it. Returns the server's representation of the tunnelEndpoint, and an error, if there is any.
func (c *tunnelEndpoints) Update(ctx context.Context, tunnelEndpoint *v1alpha1.TunnelEndpoint, opts v1.UpdateOptions) (result *v1alpha1.TunnelEndpoint, err error) {
	result = &v1alpha1.TunnelEndpoint{}
	err = c.client.Put().
		Resource("tunnelendpoints").
		Name(tunnelEndpoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tunnelEndpoint).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *tunnelEndpoints) UpdateStatus(ctx context.Context, tunnelEndpoint *v1alpha1.TunnelEndpoint, opts v1.UpdateOptions) (result *v1alpha1.TunnelEndpoint, err error) {
	result = &v1alpha1.TunnelEndpoint{}
	err = c.client.Put().
		Resource("tunnelendpoints").
		Name(tunnelEndpoint.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(tunnelEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the tunnelEndpoint and deletes it. Returns an error if one occurs.
func (c *tunnelEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tunnelendpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tunnelEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tunnelendpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched tunnelEndpoint.
func (c *tunnelEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TunnelEndpoint, err error) {
	result = &v1alpha1.TunnelEndpoint{}
	err = c.client.Patch(pt).
		Resource("tunnelendpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
