# permissions for end users to edit memberclusterinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memberclusterinfo-editor-role
rules:
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes/status
  verbs:
  - get
