# permissions for end users to view memberclusterinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memberclusterinfo-viewer-role
rules:
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes/status
  verbs:
  - get
