
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - memberclusterinfoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - tunnelendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - tunnelendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - tunnelendpoints/status
  verbs:
  - get
  - patch
  - update
