# permissions for end users to view tunnelendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnelendpoint-viewer-role
rules:
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - tunnelendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.luolanzone.io
  resources:
  - tunnelendpoints/status
  verbs:
  - get
