/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/luolanzone/tunnel-example/apis/gateway/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMemberClusterInfos implements MemberClusterInfoInterface
type FakeMemberClusterInfos struct {
	Fake *FakeGatewayV1alpha1
}

var memberclusterinfosResource = schema.GroupVersionResource{Group: "gateway.luolanzone.io", Version: "v1alpha1", Resource: "memberclusterinfos"}

var memberclusterinfosKind = schema.GroupVersionKind{Group: "gateway.luolanzone.io", Version: "v1alpha1", Kind: "MemberClusterInfo"}

// Get takes name of the memberClusterInfo, and returns the corresponding memberClusterInfo object, and an error if there is any.
func (c *FakeMemberClusterInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MemberClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(memberclusterinfosResource, name), &v1alpha1.MemberClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemberClusterInfo), err
}

// List takes label and field selectors, and returns the list of MemberClusterInfos that match those selectors.
func (c *FakeMemberClusterInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MemberClusterInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(memberclusterinfosResource, memberclusterinfosKind, opts), &v1alpha1.MemberClusterInfoList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MemberClusterInfoList{ListMeta: obj.(*v1alpha1.MemberClusterInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.MemberClusterInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested memberClusterInfos.
func (c *FakeMemberClusterInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(memberclusterinfosResource, opts))
}

// Create takes the representation of a memberClusterInfo and creates it.  Returns the server's representation of the memberClusterInfo, and an error, if there is any.
func (c *FakeMemberClusterInfos) Create(ctx context.Context, memberClusterInfo *v1alpha1.MemberClusterInfo, opts v1.CreateOptions) (result *v1alpha1.MemberClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(memberclusterinfosResource, memberClusterInfo), &v1alpha1.MemberClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemberClusterInfo), err
}

// Update takes the representation of a memberClusterInfo and updates it. Returns the server's representation of the memberClusterInfo, and an error, if there is any.
func (c *FakeMemberClusterInfos) Update(ctx context.Context, memberClusterInfo *v1alpha1.MemberClusterInfo, opts v1.UpdateOptions) (result *v1alpha1.MemberClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(memberclusterinfosResource, memberClusterInfo), &v1alpha1.MemberClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemberClusterInfo), err
}

// Delete takes name of the memberClusterInfo and deletes it. Returns an error if one occurs.
func (c *FakeMemberClusterInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(memberclusterinfosResource, name), &v1alpha1.MemberClusterInfo{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMemberClusterInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(memberclusterinfosResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MemberClusterInfoList{})
	return err
}

// Patch applies the patch and returns the patched memberClusterInfo.
func (c *FakeMemberClusterInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MemberClusterInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(memberclusterinfosResource, name, pt, data, subresources...), &v1alpha1.MemberClusterInfo{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemberClusterInfo), err
}
